OSOE-69: SCSS-building NPM script instead of Gulp task
Lombiq/Orchard-Privacy pull request #7
Opened 2022-02-23 09:27 UTC by 0liver

OSOE-69

2022-02-27 02:17 UTC, Piedone requested changes

2022-02-27 02:17 UTC, Piedone commented on package.json
> +    "lint:styles": "npm explore nodejs-extensions -- pnpm lint:styles"
Is `--` denoting a switch here? Then shouldn't be no space after it?

2022-02-27 02:17 UTC, Piedone commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
Why is one of them `pnpm` and the other `npm`?

2022-02-27 02:17 UTC, Piedone commented on package.json
> +    "lint:styles": "npm explore nodejs-extensions -- pnpm lint:styles"
If we can't get rid of having to define all of these, can we at least bundle them? I.e. have a single proxy script or something that receives all commands and redirects the to the necessary one?

2022-02-28 07:48 UTC, 0liver commented on package.json
> +    "lint:styles": "npm explore nodejs-extensions -- pnpm lint:styles"
If I remove the space, then `npm` will take `--pnpm lint:styles` as arguments. With the space the arguments `pnpm lint:styles` are passed along to `explore`.

2022-02-28 07:48 UTC, 0liver commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
`pnpm` (unfortunately?) does not have an `explore` task, so I cannot do what we do here with just `pnpm`.

2022-02-28 07:49 UTC, 0liver commented on package.json
> +    "lint:styles": "npm explore nodejs-extensions -- pnpm lint:styles"
Sounds like a valid idea - I'll investigate.

2022-02-28 13:38 UTC, Piedone commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
Does that impose the necessity of any additional installation tasks on the user, or the NPM bundled with the Node release will just work all the time?

2022-02-28 15:53 UTC, 0liver commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
As mentioned here: https://github.com/Lombiq/NodeJs-Extensions/pull/1/files#diff-1550ec65ac92f65817fc28928dfef526912b5f52356ff43651369bae92f56031R57.

2022-02-28 15:54 UTC, 0liver commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
The user will need `pnpm` anyways, to use Node.js Extensions in the first place.

2022-02-28 16:20 UTC, Piedone commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
I was referring to the NPM version, not PNPM. So I assume the answer is no?

2022-02-28 16:41 UTC, 0liver commented on package.json
> +    "clean:styles": "npm explore nodejs-extensions -- pnpm clean:styles",
Correct.

2022-02-28 16:54 UTC, Piedone commented on package.json
> +    "lint:styles": "npm explore nodejs-extensions -- pnpm lint:styles"
OK then.

2022-02-28 20:38 UTC, Piedone approved these changes

2022-03-02 19:08 UTC, Piedone approved these changes

2022-03-02 19:36 UTC, merged